# Generated by Django 3.2.6 on 2021-12-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='http://image', max_length=200),
        ),
    ]
